// <auto-generated />
using System;
using FeriadoTracker.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeriadoTracker.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119010438_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FeriadoTracker.Web.Models.Feriado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Feriados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Natal",
                            Tipo = "Nacional"
                        },
                        new
                        {
                            Id = 2,
                            Data = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Ano Novo",
                            Tipo = "Nacional"
                        },
                        new
                        {
                            Id = 3,
                            Data = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Tiradentes",
                            Tipo = "Nacional"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
